spring.application.name=BasicsSptingSecurity

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

jwt.header=Authorization
jwt.secret=jwtappdemo
jwt.expiration=3600000

